<?php  //[STAMP] 6a8836430a4cc8d29c94d57d35b7a023
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait AdvancedTester enabled:Actions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
